[package]
name = "dms"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4.39"
thiserror = "2"
actix-web = "4.9.0"
serde = { version = "1", features = ["derive"] }